### ISSUE TITLE
Internal server error for jnlp download

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/academy#10]
Hi guys,

One of our new colleagues at BiGCaT just discovered that the academy is not functioning properly.

If you click in [this](https://wikipathways.github.io/academy/stages/draw-geneproduct/) website on "launch editor", you get the following(If you click in the pop-up menu on download
):
![image](https://user-images.githubusercontent.com/26277832/50768302-3244e300-1280-11e9-9451-e44d5ee33226.png)

It happens for more pages when you need to get the jnlp webversion of PV running....

I've checked the general drag and drop for jpml from local pathvisio, that works and provides me with this:
![image](https://user-images.githubusercontent.com/26277832/50768335-4ee11b00-1280-11e9-8ed9-d8fc9a6ec257.png)

So people can still use the Academy (but it doesn't look so user friendly when at the first real practise you get an error message). I've contacted @nunogit about this as well .

**Comment by egonw** [comment]
Is it important she works on the `rcbranch` instance and not on the main WikiPathways server? (See URL in the location bar in the screenshot...)

**Comment by DeniseSl22** [comment]
I have no idea..... Just saw that it is not working (or actually, Lauren pointed it out to me when going through the Academy).

**Comment by khanspers** [comment]
I changed the link in the download script to point to the main site instead of rcbranch, it works now as far as I can tell.
