### ISSUE TITLE
Krebs cycle part of the Academy not working

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/academy#12]
There are issues with the yellow part (Setting Pathway Information Free) in the academy (https://wikipathways.github.io/academy/path.html). 

A file should open in this step: https://wikipathways.github.io/academy/stages/fig-met-1-second/ but that doesn't work. Should be rewritten to use PathVisio directly - but it is unclear which pathway should be opened.

**Comment by khanspers** [comment]
Removed Launch button and updated instructions for using PathVisio and starter pathway instead.
