### ISSUE TITLE
Add stage for illustrating phosphorylation

### ISSUE THREAD

**Issue by khanspers** [wikipathways/academy#14]
Add stage for illustrating phosphorylation to the Advanced Modeling track.

**Comment by khanspers** [comment]
A first draft has been added: https://new.wikipathways.org/academy/stages/draw-phosphorylation/
Note that the instructions for creating the structured comment on the State object are available separately as a pdf (linked to), for two reasons: it is quite long and would make the Academy stage much longer than others, and it could be useful by itself in other contexts, this makes it possible to link to it directly.

To-Do: Update the evaluation logic to check that there is indeed a Comment on the State object.

**Comment by khanspers** [comment]
Parsing of the text content in the <Comment> field of the State doesn't work as expected, for example using node.textContent. Won't/can't fix this now since the Comment will be encoded differently (easier to parse) in the upcoming new version of gpml.

**Comment by khanspers** [comment]
Improvements:

- [x]  Consider renaming this stage, "draw phosphorylation" is maybe too simplistic => updated to "draw protein phosphorylation"
- [x]  Update instructions/page layout to emphasize that there are two parts: adding the state to the node, and adding the structured comment to the state. This is not clear currently.
- [ ]  Future: Link this to a [Cytoscape tutorial](https://github.com/cytoscape/cytoscape-tutorials/issues/101) for how to map phosphoproteomics data.

**Comment by khanspers** [comment]
Updates to content based on discussion during Curator's meeting:

- [x] Add better description in Academy for how to interpret the "shorthand version", meaning the version that is currently explained
![Screen Shot 2023-07-10 at 5 17 24 PM](https://github.com/wikipathways/academy/assets/1442197/bcf85bec-098d-4d48-b3e5-c40a1544267e)

Update: It doesn't make sense to include instructions for both styles (condensed/expanded) in the same stage, because of validation. For now instructions were added to describe the difference. In the future, maybe we want a second stage "draw-protein-phosphorylation-expanded".

**Comment by khanspers** [comment]
@danidi : The instructions have been updated to include a comparison of the two styles of illustrating phosphorylations (condensed/expanded), including a description of how to interpret the condensed style, and some basic advice on when to use either style. Please review. https://academy.wikipathways.org/stages/draw-protein-phosphorylation/

**Comment by danidi** [comment]
Great, thank you @khanspers! 
Looking at both ways to draw it, I realize that the expanded style actually doesn't convey the information of inhibition of BAD. It could be interpreted as if the phosphorylated BAD is the active form, which leads to cell survival, while also the unphosphorylated BAD has an active function in progressing to apoptosis. Maybe adding another arrow from the unphosphorylated BAD to apoptosis would make this clearer, and also show the advantage of the expanded style to better indicate the function of the phosphorylation?
Also, would it make sense to add an additional inhibition arrow from AKT to unphosphorylated BAD in the extended style to make it clearer that the inhibition happens by phosphorylation? That could be a third way of drawing it (combined style?).

**Comment by khanspers** [comment]
Thanks for the feedback! 
Right, in the expanded style the inhibition/inactivation is not explicitly stated, but the downstream effect is still clear I think. (Although the interaction to "Survival" should really be dashed because it involves multiple steps, I have updated it.)
Of course in reality, both representations are simplifications, as are most pathways. What really happens (as I understand it) is that the unphosphorylated BAD is bound to BCL2L1 and BCL2 (not shown), which inactivates them. Active BCL2L1 and BCL2 would otherwise inhibit apoptosis. Phosphorylation releases the bond, and BCL2L1/BCL2 then inhibit apoptosis (drawn in the pathway as promoting survival).  
Maybe a simpler example pathway (if we can find one) would be easier to explain, for example avoiding the inhibition part? 

Im not sure I agree that adding another interaction from unphosphorylated BAD to apoptosis helps with understanding that the phosphorylated BAD is inactive. 

For your second suggestion, are you saying to add the inhibition interaction between AKT to BAD-P to the expanded style?

**Comment by danidi** [comment]
Another example could be: IRS1 activates (phosphorylates) PI3K, which then leads to AKT signaling. But here is my main issue with the condensed style: If I now want to show that PTEN inhibits PI3K, I would also draw the inhibition arrow to the phosphorylated PI3K, but in this case it would dephosphorylate instead of phosphorylate it to inactivate it. So the reader of the pathway would need to know if the protein is a kinase or a phosphatase to know how the inhibition works, that's why I found the current example a bit confusing (most of the proteins I worked with were activated by phosphorylation).
See https://classic.wikipathways.org/index.php/Pathway:WP3850 for an example pathway containing this reaction (which doesn't include the phosphorylation information at the moment).

No, I would add the inhibition interaction from AKT to the unphosphorylated (aktive) state of BAD (in the expanded style), indicating that this protein is inhibited by phosphorylating it. In the case of PTEN, it would be to the phosphorylated state of PI3K.

**Comment by khanspers** [comment]
So you mean something like this:

<img width="279" alt="Screen Shot 2023-07-13 at 5 55 10 PM" src="https://github.com/wikipathways/academy/assets/1442197/ea6b096f-a2c8-423a-9e66-4f2b4d590d9c">

I agree the IRS1 example involving PTEN is too complex to be used as the first example of how to model phosphorylation. In general, maybe that pathway should be updated to better represent the complicated regulation of PI3K. 

Here's another pathway that includes two examples, upper right corner, and the activation of CREB by ERK. The upstream part of the latter is not there (should be added), but the example could just use the ERK-CREB part:

https://classic.wikipathways.org/index.php/Pathway:WP3301

I think it would be great to get the input of other curators on this, so I added it to the agenda for the next meeting.

**Comment by Chris-Evelo** [comment]
While the above is abut how to use a pathway as an example in the Academy it also is a great example of how we would like to see a discussion page evolve and what kind of information might be added to clarify a pathway in the description. Maybe it can be used for that too?

**Comment by danidi** [comment]
yes, exactly. 
CREB activation by ERK looks good as an example. 
Yes, I agree it would be good to discuss that in the curator's meeting.

**Comment by khanspers** [comment]
It turns out that the CREB1 example isn't great because PhosphoSitePlus doesnt have any specific site information for that case. So after some searching I found this example, which is a more straightforward activation:

<img width="409" alt="draw-phosphorylation-solution" src="https://github.com/wikipathways/academy/assets/1442197/ac54c654-ccd3-47c4-ad41-12d68abe6a4a">

Inspired by Chris' comment, I re-instated the "wp-description" stage, and plan to update it with more in-depth information  about what should be included, how to deal with complex reactions/regulation etc. It will be in the path between "publish your pathway" and "add ontology terms", but since it is currently incomplete I have not updated the path yet.

**Comment by danidi** [comment]
Looks good. Would you also add the phosphorylation of EGFR and JAK, or leave it away because it is not the focus of the pathway?

**Comment by khanspers** [comment]
Good point. I added the information I could find for JAK1/JAK2 and just empty P states for EGFR since I couldnt find exactly which ones are relevant of the many EGFR phospho sites. Might update later.
I also updated the text to indicate that the stage only focuses on the STAT3 part.

**Comment by khanspers** [comment]
After trying out strategies for data mapping in Cytoscape, it was decided that the best strategy going forward is a data-driven approach (in Cytoscape). This will be described here: https://github.com/cytoscape/network-ptm-integration. Since this is outside the scope of this issue, I will close this for now.
