### ISSUE TITLE
Add stage for sex-specific annotations GPML2021

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/academy#18]
See [paper](https://doi.org/10.1038/s41592-021-01168-6) on annotating omics databases with sex specific information (and in passing age and ethnicity is also mentioned).

ECO doesn't seem to have terms for this, I used the following keywords:
- female, male, gender, sex
- ethnicity, race, Caucasian, African
- age, time 

There is one section on species:
![image](https://user-images.githubusercontent.com/26277832/123542211-a02f3e80-d748-11eb-93d6-79437d14c8ea.png)

I've tried to find other ontologies describing the above, but to no success... So, in order to structure this information in the future in the GPML2021 scheme, I think we should contact the ECO people and ask them to include terms for sex,age and ethnicity annotations.

**Comment by DeniseSl22** [comment]
See [issue](https://github.com/evidenceontology/evidenceontology/issues/278) asking ECO team for extending their ontology.

**Comment by DeniseSl22** [comment]
@khanspers , may I ask why this issue was closed? I don't see any comments on resolving this?

**Comment by AlexanderPico** [comment]
The linked issue that this one depended upon was closed due to this response from ECO folks:
> Upon further review of this issue, we don't think the types of terms you are looking for (e.g. "male-sex biased...") are a good fit for ECO. They don't seem to be evidence for an assertion so much as modifiers to attach to results (which themselves might be evidence for an assertion.)

A feature request for new GPML functionality probably should go here: https://github.com/PathVisio/GPML/issues

I think this issue about adding an academy step should be closed until we first figure out if we can even add this information. Sound good?

**Comment by DeniseSl22** [comment]
Agreed, I've added this point in the GPML Pathvisio issue tracker, https://github.com/PathVisio/GPML/issues/88
