### ISSUE TITLE
Add checking of Jenkins reports to the QA protocol

### ISSUE THREAD

**Issue by khanspers** [wikipathways/academy#20]
From WP meeting notes 2022-04-27, it would be good to have some of the Jenkins reports be reviewed as part of the weekly curation report, as an extra task if there is time. It could go here: https://new.wikipathways.org/academy/stages/qaprotocol-extra/index.html

**Comment by khanspers** [comment]
Some notes on what the curator should do for each test:

1. [unknownTypes](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/DataNodes/unknownTypes/): Open the relevant pathway in PathVisio using WPID, then find the problematic node by the label listed in the Jenkins report. If it's clear what the node should be, assign it (Can use type converter). If it's not a data node, redraw as graphical element.
2. [weirdCharacterTitles](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/General/weirdCharacterTitles/): Update title at WP
3. [duplicateTitles](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/General/duplicateTitles_3/): Review the affected pathways to compare them. If one is just a copy of the other with no other new information, delete it. If the pathways are unique, update one of the titles to better reflect the content.
4. [unreviewedIdentifiers](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/UniProt/unreviewedIdentifiers/): The report includes instructions on what to do.
5. [possibleTranslocations](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/Interactions/possibleTranslocations/): Remodel based on [this](https://new.wikipathways.org/academy/stages/draw-transport/).
6. [tooManyInChIKeys](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/Metabolites/tooManyInChIKeys_3/): Not sure what curators should do here. Figure out which InChiKey is relevant? 
7. Lots of tasks for "withoutMapping", for example [chebiWithoutMapping](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/Wikidata/chebiWithoutMapping_4/). Anything we can do with these? It's a problem with the database right? 
8. [interactionsWithLabels](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/Interactions/interactionsWithLabels/): Many of these are legitimate, i.e. a protein/gene product leading to something like another process, regulating a specific process etc. What should the curator do here?
9. [atLeastOneReference](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/References/atLeastOneReference_3/), basically pathways with zero literature references. The task here might be pretty difficult, since the curator is presumably not an expert. If a paper is referenced in the description its easy. If not, I'm not sure what our recommendation should be here.

**Comment by khanspers** [comment]
Started a new stage here (draft): https://new.wikipathways.org/academy/stages/task-jenkins/

**Comment by khanspers** [comment]
Two ideas of how to incorporate this:
1. Add this as an optional stage to the existing qa protocol
2. Split this into several stages/tasks and create a new Academy track for it, something like "Advanced curation"

**Comment by egonw** [comment]
> 1. [unknownTypes](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/DataNodes/unknownTypes/): Open the relevant pathway in PathVisio using WPID, then find the problematic node by the label listed in the Jenkins report. If it's clear what the node should be, assign it (Can use type converter). If it's not a data node, redraw as graphical element.

Agreed. We should clarify what should be a Label and what not.

> 2. [weirdCharacterTitles](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/General/weirdCharacterTitles/): Update title at WP

@DeniseSl22 had questions about the current allowed characters; we should revisit that in the next WP telcon where Alex, Tina, and Denise are present. 

> 3. [duplicateTitles](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/General/duplicateTitles_3/): Review the affected pathways to compare them. If one is just a copy of the other with no other new information, delete it. If the pathways are unique, update one of the titles to better reflect the content.

Sounds good.

> 4. [unreviewedIdentifiers](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/UniProt/unreviewedIdentifiers/): The report includes instructions on what to do.

Do the instructions make enough sense? 

> 5. [possibleTranslocations](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/Interactions/possibleTranslocations/): Remodel based on [this](https://new.wikipathways.org/academy/stages/draw-transport/).

What if the translocation is diffusion (not common in WP), or from one part inside the cell to another (quite common)?

> 6. [tooManyInChIKeys](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/Metabolites/tooManyInChIKeys_3/): Not sure what curators should do here. Figure out which InChiKey is relevant?

Ah, this one is a good example that should be left to a subset of curators (Denise and me, in this case). See my comment in my email about defining which tests we want to have the weekly curators look at.

> 7. Lots of tasks for "withoutMapping", for example [chebiWithoutMapping](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/Wikidata/chebiWithoutMapping_4/). Anything we can do with these? It's a problem with the database right?

This one is one that has kept Denise and me busy. The reason these things pop up are diverse. The identifier can be outdated or not exist, it may not be mapped in BridgeDb (important for data analysis).

This one is another one that only a subset of curators should get, I think.

> 8. [interactionsWithLabels](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/Interactions/interactionsWithLabels/): Many of these are legitimate, i.e. a protein/gene product leading to something like another process, regulating a specific process etc. What should the curator do here?

If they are legitimate (like to another process) and the Label of that process should likely be converted into a DataNode @Type="Pathway" (or Unknown).

In some cases I can imagine converted the Interaction into a graphical arrow could make sense too.

> 9. [atLeastOneReference](https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation/lastCompletedBuild/testReport/nl.unimaas.bigcat.wikipathways.curator/References/atLeastOneReference_3/), basically pathways with zero literature references. The task here might be pretty difficult, since the curator is presumably not an expert. If a paper is referenced in the description its easy. If not, I'm not sure what our recommendation should be here.

The curator action could be to contact the original author?

**Comment by egonw** [comment]
> Two ideas of how to incorporate this:
> 
> 1. Add this as an optional stage to the existing qa protocol
> 2. Split this into several stages/tasks and create a new Academy track for it, something like "Advanced curation"

Yes, the optional here is important. Any single small thing they improve is great! Fixing all of them is impossible and some take a lot of effort.

**Comment by khanspers** [comment]
In the new (planned) system where pathway edits will be PRs, many of these tests should be possible to do as automated tests on the gpml, before the PR is sent to a curator for review. For example tests 1,2,3,9 at least. Closing this since automated tests and the curator's QA protocol will both be redesigned over the next few months.
