### ISSUE TITLE
License CC BY 4.0 okay?

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/academy#21]
@AlexanderPico @khanspers 
which license should we use for the academy material?

**Comment by khanspers** [comment]
I'm not sure which license was chosen when the repo was created, maybe "None". I can't see it at GH, normally its displayed at the top. Do you mean that we should add a license at GH? I don't know how to do that.
I would guess if we were to specify a license (or change it from something else), we would use Creative Commons Zero v 1.0 Universal?

**Comment by Chris-Evelo** [comment]
I think for the Academy both C0 and CCBy would be fine. But if you do want to go with CCBy, and even if you do not maybe,  we might want to think about also giving some "How to Cite" advice?

**Comment by khanspers** [comment]
I added a license (https://github.com/wikipathways/academy/blob/gh-pages/LICENSE), CC-BY 4.0 was not an option for the template so I picked CC0. We can change it if necessary.
