### ISSUE TITLE
Add information on where to download the BridgeDb files to installation instructions in academy

### ISSUE THREAD

**Issue by danidi** [wikipathways/academy#34]
http://academy.wikipathways.org/stages/walk-install-pv/ describes how to install the BridgeDB plugin, but not the database. It allows searching for Gene names, but protein names give an error if the database is not installed. See https://docs.google.com/document/d/14Qe54Eb-Yz3RfLLDnBV3tRNwX0PcJOX5OLUknSMINzU/edit for details on installation.

**Comment by danidi** [comment]
Actually this didn't solve my issue of receiving an error message while searching for a protein name in a protein datanode. So not sure if it really helps.

**Comment by khanspers** [comment]
Just to confirm, downloading bridgeDB files **doesn't** solve the problem? So no need to update instructions? 

I've never actually tried searching for protein name. @danidi are you saying that searching for "Frizzled-5" instead of "FZD5" is what you want to do? => nevermind I see the problem in Slack now.

**Comment by danidi** [comment]
Exactly, it doesn't solve the problem. I left the issue open for now, because I don't know what the exact advantage of having the BridgeDB file downloaded would be. Maybe @egonw or @mkutmon can comment on this?
Exactly, if I search for example for Frizzled-5 I get an "Exception occurred while searching, see error log for details" error message. I will follow up on this next week if that is expected behaviour, and maybe create a pathvisio issue instead.

**Comment by danidi** [comment]
As discussed in todays meeting, the download is only necessary in specific use-cases. So no need to have it in the general tutorial.
