### ISSUE TITLE
End Academy's last step with a finish button

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/academy#39]
@khanspers : the last step of the Academy now doesn't have a button to take them back to the overview page (iso the 'next button' at the bottom right), or to a celebratory page with confetti or something stating 'you're all done, congrats'.... What do you think ?
We could also do a page where they can claim a 'curation expert' diploma or something in the future as well (if we can link the academy to GitHub accounts?

**Comment by khanspers** [comment]
Good idea. I will see what I can come up with.

**Comment by khanspers** [comment]
Comment about a potential WP Academy at GitHub "diploma": As of now (Sep 2023) GitHub doesn't allow for custom achievement badges, so I don't think this is possible.

**Comment by AlexanderPico** [comment]
The reward could be that they are automatically added to the Reviewer-of-the-Week roster! 😜 

But, seriously, we should definitely congratulate and celebrate them, and also let them know they've unlocked the first step in becoming an official reviewer for WikiPathways. We should have transparent process for accepting new reviewers, like a progression ladder (once we make up what the steps are).

**Comment by DeniseSl22** [comment]
> We should have transparent process for accepting new reviewers, like a progression ladder (once we make up what the steps are).

Agreed!!

**Comment by khanspers** [comment]
First draft here: https://academy.wikipathways.org/stages/task-success/

Once we define and describe our process of accepting new reviewers, this should be added also. I will bring it up on one of the Community Curation meetings.

**Comment by khanspers** [comment]
- Renamed the stage (although users dont really see it anyway....): https://academy.wikipathways.org/stages/draw-success/
- Added to path
