### ISSUE TITLE
Track pathways viewed per task

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/academy#4]
We currently provide a counter for content tagged, e.g., "4 pathways remaining". In cases like Under Construction, it's often appropriate to complete the task and leave 4 pathways with the tag. It would be nice to improve the counter to also track pathways viewed (or yet to be reviewed), e.g., "3 of 4 remaining pathway to be reviewed".

Not sure how to implement this with current load/display/count logic...

**Comment by khanspers** [comment]
This will not be relevant with the site and new PR system for QA protocol. Closing.
