### ISSUE TITLE
Expand instructions for adding lit refs to include ISBN, DOI and basic URL.

### ISSUE THREAD

**Issue by khanspers** [wikipathways/academy#44]
[Existing instructions](https://academy.wikipathways.org/stages/met-1-add-literature/) should be expanded to include details on how to use DOI, ISBN and URL as references. See https://github.com/wikipathways/wikipathways.github.io/issues/89

**Comment by khanspers** [comment]
See https://github.com/wikipathways/wikipathways-database/tree/main/scripts/generate-references

**Comment by khanspers** [comment]
Created a new stage, which would be added in the pink "advanced" track: https://academy.wikipathways.org/stages/draw-advanced-literature/

It would be great if others could review if these instructions make sense before finalizing: @susancoort @egonw

**Comment by susancoort** [comment]
@khanspers Clear instructions for adding a literature reference - advanced. 

Suggestions: 
- In the table, center the heading "Identifier example" 
- For the description of adding information for the DOI reference I would use the order given:, see below
![image](https://github.com/user-attachments/assets/4c930a3c-2688-4f57-a09e-261b5fbdfecb)
- Should we mention that the **Source** field will be empty?
- Although I only added the literature reference once it was in the gpml file twice. 
- In addition to the instructions, I changed the year of the reference and saved it again. When checking the gpml in the text editor I noticed that a new reference is added and you need to change **Pubmed in DOI again**.

**Comment by khanspers** [comment]
Thanks @susancoort! Great feedback, I updated the instructions. 

I tried the instructions again and I don't get the duplicated reference, either by updating the publication year or not.

**Comment by egonw** [comment]
Looks good to me too. Reads well, and pretty clear, I think. Maybe the table can have the header in bold?

**Comment by khanspers** [comment]
Thanks for all the feedback! I have added this as a step in Advanced track.
