### ISSUE TITLE
Describe how to use WikiData identifier for data node type "Unknown"

### ISSUE THREAD

**Issue by khanspers** [wikipathways/academy#49]
As discussed in 12/12 Community Curation meeting, it is sometimes necessary to add a node of type Unknown, which can be annotated with WikiData identifier, instead of leaving it blank.

Could potentially here https://academy.wikipathways.org/stages/fig-met-1-third/index.html (for "Fatty acids and lipids").

**Comment by AlexanderPico** [comment]
Aren't fatty acids and lipids `Metabolites`?

**Comment by khanspers** [comment]
Yeah, this is a bad example. In fact this stage should be updated to add two grouped metabolite nodes instead of the graphical label. 
None of our existing stages is a good fit for this, so this will need to be a new stage. The example discussed in the curators meeting involved how to represent a biological process ("excretion via urine"); I will either use that example, or find another one.

**Comment by khanspers** [comment]
Potential pathways to use:
https://www.wikipathways.org/pathways/WP4030.html (center right portion with lipolysis -> lipid storage)
https://www.wikipathways.org/pathways/WP4814.html (see https://www.semanticscholar.org/paper/Mechanism-of-Sex-Determination-in-Humans%3A-Insights-Bashamboo-McElreavey/2d180748b6f2b2e1ed5ee41b21e0add41318026c)

**Comment by khanspers** [comment]
New stage here: https://academy.wikipathways.org/stages/draw-unknown-node/

**Comment by khanspers** [comment]
@egonw: Please review if you have time.

**Comment by egonw** [comment]
@khanspers, looks good to me!

The next are just follow-up thoughts and do not require changes, and are future ideas (ie. you decide if this is the time to do something with it or later).

I am wondering if we can use information from Wikidata to specify the "unknown"-ness. GPML allows other `DataNode` types, and maybe we could have a short table with some more common Wikidata "types" and their mappings to `DataNode` types. For example, `Q189118` could map to something like "Cell" as DataNode type.

I also realize that this "Wikidata trick" can also be used for metabolite (classes) and protein families of protein classes (like "flippase", cc @mkutmon) and then too, you would probably want to change `Unknown` to something more specific.

**Comment by khanspers** [comment]
Thanks for the feedback and great idea. It would involve updating the GPML manually to switch Unknown to a Wikidata id?

I will add the stage as-is to the path for now, we can update it later.

**Comment by khanspers** [comment]
One thing: I don't really like the title "Draw Unknown Node". @egonw do you have suggestions for a better title? Some ideas
"Draw non-standard node"
"Draw cell type" (maybe not great since we also represent cells with graphical objects)
"Annotating nodes with Wikidata"

**Comment by Chris-Evelo** [comment]
What about "Annotating non-standard nodes with Wikidata"?

**Comment by khanspers** [comment]
Updated titled to "Annotating Non-standard Nodes".
