### ISSUE TITLE
Add quality tag item counts into display

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/academy#5]
E.g., for unconnected lines and missing xrefs. Display the counts so users can tell whether it's a quick fix or not.

**Comment by khanspers** [comment]
Looking at the code, it seems like this would require a new function (something like getCurationDetails) that collects this using "getCurationTagsByName", then call this function from showNext(). Does that sound right @AlexanderPico ?

**Comment by khanspers** [comment]
This is no longer necessary since we will be switching away from the current QA protocol soon with the launch of the new WP website.
