### ISSUE TITLE
Add task in taskfeed.js to find pathways with no tags (going back 60 days)

### ISSUE THREAD

**Issue by khanspers** [wikipathways/academy#7]
Some pathways have no quality tags at all, and are therefor difficult to find and are essentially orphaned pathways. The idea is to create a js task to look for these tasks, going back 60 days.

**Comment by khanspers** [comment]
This can be done with rWikiPathways, and should be done periodically, but should probably not be part of the weekly protocol. 
https://github.com/wikipathways/rWikiPathways

**Comment by Chris-Evelo** [comment]
We might want to have a "pathway is a stub" tag for things that are not real pathways yet, but that still contain a nudge of valuable information that could become part of a useful pathway in the future. In principle that tag should prevent it from going in any analysis collection (but we might want to use it when building networks or in the RDF.
