### ISSUE TITLE
Add table view for QA tasks

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/academy#8]
Should be able to build a table from the initial query where we gather the total count... maybe. We currently just grab 10 pathways as a time, so we might not have a lot of information about each pathway from just the count query. I guess we would need the pathway name and url at a minimum.

This could be a tab or toggle view switch: sequential images or table

The table should also include an interactive column where the user could indicate that they've viewed/fixed a particular pathway. Analogous to how "next pathway" currently works, but in the table view perhaps a simple 'X' or 'check mark' icon that then changes the style of (or hides) the row.

**Comment by mkutmon** [comment]
maybe we should add some curation specific webservice functions. we could design those that they provide everything needed for the table, e.g. only include pathways tagged with under constructions not edited for more than 30 days. So we immediately focus on those pathways that we should curate. We had these kind of tables on mediawiki, so I don't think it should take too much time to implement such a method. I'll try to find some time to look into this.

**Comment by khanspers** [comment]
This overlaps with new content on https://academy.wikipathways.org/stages/task-needs-work/ to have curators sign up to specific pathways using GH issues. Closing this.
