### ISSUE TITLE
"Curator of the week" empty on WPs website

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/academy#9]

**Comment by mkutmon** [comment]
Good catch. I'll need to go through it today anyway. I'll update the XML then and see if it fixes the problem.

**Comment by mkutmon** [comment]
I know what happened. Mirella by accident copied the <item> tag from the next person to the end and then the XML was invalid. Should be updated within the next hour or so, I think.

**Comment by DeniseSl22** [comment]
Ah okay,
Yeah I was awake enough to see it wasn't working, but not awake enough to find the mistake in the XML file.
Good you are ;)
